name: testar codin
on:
  push:
    branches:
      - master
jobs:
  build:    
    runs-on: ubuntu-latest  # Adicionado recuo aqui
    steps:                  # Adicionado recuo aqui
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: executar script com argumentos
        run: python plus.py 3 4
